/**
 * Boutique — 2D catalog dataset for the e-commerce style catalog UI
 * (grid, filters, cart). Separate from the 3D hero ring defined in
 * productData.js: the 8 hero products are re-expressed here as the
 * `-01` entry of their category, surrounded by invented siblings and
 * variants of the same Hakkilo XR product lines.
 *
 * Each `category` maps 1:1 to a key of PRODUCT_MODELS in
 * ProductModels.jsx, so every catalog card can reuse its category's
 * existing primitive 3D preview.
 */

export const CATALOG_CATEGORIES = [
    { id: 'headset', label: 'Casques VR' },
    { id: 'glasses', label: 'Lunettes AR' },
    { id: 'console', label: 'Consoles de jeu' },
    { id: 'drone', label: 'Drones' },
    { id: 'scanner3d', label: 'Scanners 3D' },
    { id: 'controller', label: 'Contrôleurs XR' },
    { id: 'basestation', label: 'Bases de tracking' },
    { id: 'hapticglove', label: 'Gants haptiques' },
];

export const CATALOG_PRODUCTS = [
    // ── Casques VR ────────────────────────────────────────────────
    {
        id: 'headset-01',
        category: 'headset',
        nom: 'Hakkilo One',
        prix: 520000,
        stock: 14,
        note: 4.6,
        desc: "Notre casque autonome de référence, avec suivi 6DoF, résolution 4K par œil et 3 heures d'autonomie pour la formation comme l'exploration.",
        nouveaute: false,
    },
    {
        id: 'headset-02',
        category: 'headset',
        nom: 'Hakkilo One Pro',
        prix: 650000,
        stock: 6,
        note: 4.8,
        desc: "La version studio du One : optiques pancake, suivi oculaire et mousse faciale lavable pensée pour les sessions longues en salle de formation.",
        nouveaute: false,
    },
    {
        id: 'headset-03',
        category: 'headset',
        nom: 'Hakkilo One Lite',
        prix: 260000,
        stock: 27,
        note: 4.2,
        desc: "Un casque allégé et entièrement réparable en atelier agréé, idéal pour équiper une classe entière sans exploser le budget.",
        nouveaute: false,
    },
    {
        id: 'headset-04',
        category: 'headset',
        nom: 'Hakkilo Focus',
        prix: 445000,
        stock: 11,
        note: 4.4,
        desc: "Conçu pour l'entreprise, le Focus embarque un mode kiosque verrouillé et une ventilation renforcée qui tient les après-midi de grande chaleur.",
        nouveaute: false,
    },
    {
        id: 'headset-05',
        category: 'headset',
        nom: 'Hakkilo One S2',
        prix: 580000,
        stock: 9,
        note: 4.7,
        desc: "Deuxième génération du One : châssis affiné, dalles plus lumineuses et sangle arrière en cuir travaillé par nos ateliers partenaires de Dakar.",
        nouveaute: true,
    },
    {
        id: 'headset-06',
        category: 'headset',
        nom: 'Hakkilo Kibo',
        prix: 185000,
        stock: 33,
        note: 3.9,
        desc: "Le casque d'initiation du catalogue, robuste et sans fioritures, distribué en priorité aux écoles et clubs XR du réseau Hakkilo.",
        nouveaute: false,
    },

    // ── Lunettes AR ───────────────────────────────────────────────
    {
        id: 'glasses-01',
        category: 'glasses',
        nom: 'Hakkilo Lens',
        prix: 240000,
        stock: 18,
        note: 4.5,
        desc: "Des lunettes connectées légères à l'affichage discret, avec une autonomie qui couvre toute la journée de travail.",
        nouveaute: false,
    },
    {
        id: 'glasses-02',
        category: 'glasses',
        nom: 'Hakkilo Lens S2',
        prix: 295000,
        stock: 12,
        note: 4.7,
        desc: "La nouvelle Lens gagne un champ de vision élargi et des branches ajustables sans outil, appréciées lors des tournées de maintenance.",
        nouveaute: true,
    },
    {
        id: 'glasses-03',
        category: 'glasses',
        nom: 'Hakkilo Lens Lite',
        prix: 120000,
        stock: 31,
        note: 4.0,
        desc: "Monture simplifiée et affichage monochrome pour les notifications essentielles, à un prix pensé pour les jeunes actifs.",
        nouveaute: false,
    },
    {
        id: 'glasses-04',
        category: 'glasses',
        nom: 'Hakkilo Lens Pro',
        prix: 340000,
        stock: 5,
        note: 4.8,
        desc: "Verres photochromiques, correction sur mesure et micros directionnels : la Lens des architectes et des chefs de chantier.",
        nouveaute: false,
    },
    {
        id: 'glasses-05',
        category: 'glasses',
        nom: 'Hakkilo Sahel',
        prix: 210000,
        stock: 22,
        note: 4.3,
        desc: "Une édition pensée pour la forte luminosité sahélienne, avec verres teintés haute lisibilité et traitement anti-poussière des charnières.",
        nouveaute: false,
    },
    {
        id: 'glasses-06',
        category: 'glasses',
        nom: 'Hakkilo Lens Work',
        prix: 265000,
        stock: 15,
        note: 4.4,
        desc: "Certifiées pour le port sur chantier, ces lunettes affichent plans et consignes de sécurité directement dans le champ de vision de l'opérateur.",
        nouveaute: false,
    },

    // ── Consoles de jeu ───────────────────────────────────────────
    {
        id: 'console-01',
        category: 'console',
        nom: 'Hakkilo Play',
        prix: 390000,
        stock: 16,
        note: 4.5,
        desc: "Une console compacte compatible avec tout le catalogue Hakkilo XR, pensée pour les expériences interactives en boutique comme en formation.",
        nouveaute: false,
    },
    {
        id: 'console-02',
        category: 'console',
        nom: 'Hakkilo Play Pro',
        prix: 640000,
        stock: 7,
        note: 4.8,
        desc: "Le haut de gamme du salon : processeur graphique renforcé, stockage doublé et refroidissement silencieux calibré pour les climats chauds.",
        nouveaute: false,
    },
    {
        id: 'console-03',
        category: 'console',
        nom: 'Hakkilo Play Lite',
        prix: 225000,
        stock: 29,
        note: 4.1,
        desc: "Toute la ludothèque Hakkilo dans un boîtier réduit qui fonctionne aussi sur batterie externe, pratique là où le réseau électrique fluctue.",
        nouveaute: false,
    },
    {
        id: 'console-04',
        category: 'console',
        nom: 'Hakkilo Arcade',
        prix: 780000,
        stock: 3,
        note: 4.6,
        desc: "La borne des espaces de jeu et des boutiques partenaires, livrée avec habillage bois personnalisable réalisé par des menuisiers locaux.",
        nouveaute: false,
    },
    {
        id: 'console-05',
        category: 'console',
        nom: 'Hakkilo Play Duo',
        prix: 460000,
        stock: 13,
        note: 4.4,
        desc: "Le pack familial : une Play accompagnée de deux manettes et d'une sélection de jeux coopératifs créés par des studios du continent.",
        nouveaute: true,
    },
    {
        id: 'console-06',
        category: 'console',
        nom: 'Hakkilo Studio Dock',
        prix: 720000,
        stock: 4,
        note: 4.7,
        desc: "Station de développement pour créateurs, avec ports de débogage exposés et documentation complète en français et en anglais.",
        nouveaute: false,
    },

    // ── Drones ────────────────────────────────────────────────────
    {
        id: 'drone-01',
        category: 'drone',
        nom: 'Hakkilo ScanFly',
        prix: 850000,
        stock: 8,
        note: 4.7,
        desc: "Drone autonome à capteurs LiDAR et caméras haute résolution pour numériser des environnements entiers et créer des jumeaux numériques fidèles.",
        nouveaute: false,
    },
    {
        id: 'drone-02',
        category: 'drone',
        nom: 'Hakkilo ScanFly Mini',
        prix: 320000,
        stock: 21,
        note: 4.2,
        desc: "Moins de 900 grammes au décollage : le ScanFly de poche pour cartographier cours, ateliers et petites parcelles sans licence lourde.",
        nouveaute: false,
    },
    {
        id: 'drone-03',
        category: 'drone',
        nom: 'Hakkilo ScanFly Pro',
        prix: 950000,
        stock: 2,
        note: 4.9,
        desc: "Double capteur LiDAR, 45 minutes de vol et transfert des relevés vers la suite Hakkilo avant même le retour au sol.",
        nouveaute: true,
    },
    {
        id: 'drone-04',
        category: 'drone',
        nom: 'Hakkilo Harmattan',
        prix: 610000,
        stock: 10,
        note: 4.5,
        desc: "Baptisé d'après le vent qu'il affronte, ce drone à moteurs gainés vole par forte poussière et se démonte sans outil pour l'entretien.",
        nouveaute: false,
    },
    {
        id: 'drone-05',
        category: 'drone',
        nom: 'Hakkilo ScanFly Agri',
        prix: 540000,
        stock: 17,
        note: 4.3,
        desc: "Capteurs multispectraux et plans de vol préprogrammés pour suivre l'état des cultures et alimenter les coopératives agricoles en relevés précis.",
        nouveaute: false,
    },
    {
        id: 'drone-06',
        category: 'drone',
        nom: 'Hakkilo ScanFly Coast',
        prix: 700000,
        stock: 6,
        note: 4.4,
        desc: "Traitement anticorrosion et flotteurs amovibles : la variante des littoraux, du port d'Abidjan aux mangroves de Casamance.",
        nouveaute: false,
    },

    // ── Scanners 3D ───────────────────────────────────────────────
    {
        id: 'scanner3d-01',
        category: 'scanner3d',
        nom: 'Hakkilo ScanHand',
        prix: 720000,
        stock: 9,
        note: 4.6,
        desc: "Scanner laser portable de qualité métrologique qui capture les objets physiques avec une précision submillimétrique pour les scènes XR.",
        nouveaute: false,
    },
    {
        id: 'scanner3d-02',
        category: 'scanner3d',
        nom: 'Hakkilo ScanHand Pro',
        prix: 1100000,
        stock: 2,
        note: 4.9,
        desc: "La référence des bureaux d'études : précision certifiée à 0,02 mm, capture des surfaces sombres et étalonnage assuré par notre laboratoire d'Accra.",
        nouveaute: false,
    },
    {
        id: 'scanner3d-03',
        category: 'scanner3d',
        nom: 'Hakkilo ScanHand Lite',
        prix: 340000,
        stock: 19,
        note: 4.1,
        desc: "Un scanner d'entrée de gamme qui se branche directement sur smartphone, parfait pour documenter collections et inventaires de musée.",
        nouveaute: false,
    },
    {
        id: 'scanner3d-04',
        category: 'scanner3d',
        nom: 'Hakkilo ScanTable',
        prix: 480000,
        stock: 12,
        note: 4.4,
        desc: "Plateau tournant motorisé et éclairage calibré pour numériser en série sculptures, poteries et pièces d'artisanat destinées à la vente en ligne.",
        nouveaute: true,
    },
    {
        id: 'scanner3d-05',
        category: 'scanner3d',
        nom: 'Hakkilo ScanRoom',
        prix: 980000,
        stock: 4,
        note: 4.7,
        desc: "Monté sur trépied, il relève des pièces entières en quelques minutes et exporte des plans exploitables par architectes et notaires.",
        nouveaute: false,
    },
    {
        id: 'scanner3d-06',
        category: 'scanner3d',
        nom: 'Hakkilo ScanHand S2',
        prix: 800000,
        stock: 7,
        note: 4.5,
        desc: "Le ScanHand nouvelle génération gagne une poignée rééquilibrée, une batterie interchangeable à chaud et un maillage nettoyé en temps réel.",
        nouveaute: false,
    },

    // ── Contrôleurs XR ────────────────────────────────────────────
    {
        id: 'controller-01',
        category: 'controller',
        nom: 'Hakkilo Touch',
        prix: 95000,
        stock: 26,
        note: 4.5,
        desc: "Paire de contrôleurs ergonomiques au suivi infrarouge précis et au retour tactile nuancé, compagnons naturels du casque Hakkilo One.",
        nouveaute: false,
    },
    {
        id: 'controller-02',
        category: 'controller',
        nom: 'Hakkilo Touch Pro',
        prix: 140000,
        stock: 10,
        note: 4.7,
        desc: "Gâchettes réglables, batteries remplaçables et coques interchangeables : les contrôleurs que nos centres de formation usent sans les casser.",
        nouveaute: false,
    },
    {
        id: 'controller-03',
        category: 'controller',
        nom: 'Hakkilo Touch Lite',
        prix: 50000,
        stock: 38,
        note: 3.8,
        desc: "L'essentiel du Touch à petit prix, avec une prise en main pensée pour les plus jeunes et les ateliers de découverte.",
        nouveaute: false,
    },
    {
        id: 'controller-04',
        category: 'controller',
        nom: 'Hakkilo Grip',
        prix: 115000,
        stock: 14,
        note: 4.4,
        desc: "Un contrôleur en forme d'outil qui reproduit le poids et la prise d'une perceuse ou d'un fer à souder pour la formation aux métiers techniques.",
        nouveaute: false,
    },
    {
        id: 'controller-05',
        category: 'controller',
        nom: 'Hakkilo Touch S2',
        prix: 120000,
        stock: 20,
        note: 4.6,
        desc: "Nouvelle génération à capteurs de pression sur toute la poignée, qui distingue une caresse d'une prise ferme sans le moindre bouton.",
        nouveaute: true,
    },
    {
        id: 'controller-06',
        category: 'controller',
        nom: 'Hakkilo Baton',
        prix: 65000,
        stock: 0,
        note: 4.0,
        desc: "Un pointeur fin taillé pour les conférences et visites virtuelles guidées, avec trois semaines d'autonomie sur une seule charge.",
        nouveaute: false,
    },

    // ── Bases de tracking ─────────────────────────────────────────
    {
        id: 'basestation-01',
        category: 'basestation',
        nom: 'Hakkilo Anchor',
        prix: 130000,
        stock: 15,
        note: 4.5,
        desc: "Borne de tracking à balayage laser garantissant une synchronisation millimétrique pour les salles VR multi-utilisateurs.",
        nouveaute: false,
    },
    {
        id: 'basestation-02',
        category: 'basestation',
        nom: 'Hakkilo Anchor Pro',
        prix: 190000,
        stock: 8,
        note: 4.8,
        desc: "Couverture portée à 12 mètres et chaînage de six bornes pour suivre des plateaux entiers, entrepôts et scènes de spectacle compris.",
        nouveaute: false,
    },
    {
        id: 'basestation-03',
        category: 'basestation',
        nom: 'Hakkilo Anchor Mini',
        prix: 65000,
        stock: 34,
        note: 4.0,
        desc: "Une base de bureau qui se visse ou se pose sur une étagère, suffisante pour un poste de travail XR individuel.",
        nouveaute: false,
    },
    {
        id: 'basestation-04',
        category: 'basestation',
        nom: 'Hakkilo Anchor Duo',
        prix: 175000,
        stock: 11,
        note: 4.6,
        desc: "Le pack de deux bornes pré-appairées avec fixations murales incluses, installé en moins d'une heure par nos revendeurs agréés.",
        nouveaute: false,
    },
    {
        id: 'basestation-05',
        category: 'basestation',
        nom: 'Hakkilo Beacon',
        prix: 160000,
        stock: 6,
        note: 4.3,
        desc: "Première base d'extérieur du catalogue, étanche et stable de 5 à 50 degrés, pour les parcours AR en plein air et les marchés couverts.",
        nouveaute: true,
    },
    {
        id: 'basestation-06',
        category: 'basestation',
        nom: 'Hakkilo Anchor S2',
        prix: 150000,
        stock: 18,
        note: 4.4,
        desc: "L'Anchor repensé : moteur de balayage plus silencieux, consommation réduite de moitié et coque en plastique recyclé moulée à Lomé.",
        nouveaute: false,
    },

    // ── Gants haptiques ───────────────────────────────────────────
    {
        id: 'hapticglove-01',
        category: 'hapticglove',
        nom: 'Hakkilo Glove',
        prix: 430000,
        stock: 7,
        note: 4.6,
        desc: "Gant professionnel à retour de force qui restitue textures, formes et résistance des objets virtuels, plébiscité en chirurgie et en maintenance.",
        nouveaute: false,
    },
    {
        id: 'hapticglove-02',
        category: 'hapticglove',
        nom: 'Hakkilo Glove Pro',
        prix: 520000,
        stock: 3,
        note: 4.9,
        desc: "Vingt-quatre points de retour par main et suivi de chaque phalange : la précision exigée par les simulateurs médicaux les plus stricts.",
        nouveaute: false,
    },
    {
        id: 'hapticglove-03',
        category: 'hapticglove',
        nom: 'Hakkilo Glove Lite',
        prix: 195000,
        stock: 23,
        note: 4.1,
        desc: "Les vibrations essentielles sans le retour de force complet, dans un gant lavable en machine qui passe de main en main sans souci.",
        nouveaute: false,
    },
    {
        id: 'hapticglove-04',
        category: 'hapticglove',
        nom: 'Hakkilo Glove Med',
        prix: 490000,
        stock: 5,
        note: 4.7,
        desc: "Décliné en trois tailles stériles avec doublures jetables, il équipe déjà plusieurs facultés de médecine partenaires en Afrique de l'Ouest.",
        nouveaute: false,
    },
    {
        id: 'hapticglove-05',
        category: 'hapticglove',
        nom: 'Hakkilo Glove S2',
        prix: 460000,
        stock: 9,
        note: 4.8,
        desc: "Nouvelle génération à moteurs miniaturisés, plus légère de 80 grammes et refroidie passivement pour rester confortable en saison chaude.",
        nouveaute: true,
    },
    {
        id: 'hapticglove-06',
        category: 'hapticglove',
        nom: 'Hakkilo Weave',
        prix: 280000,
        stock: 16,
        note: 4.3,
        desc: "Un gant textile dont la maille est tissée par nos ateliers partenaires de Bouaké, réparable au fil et à l'aiguille comme un vêtement.",
        nouveaute: false,
    },
];
